package ast;

public enum NodeKind {
    PROGRAM_NODE,

    FUNCTION_DECLARATION_NODE,
    FOR_DECLARATION_NODE,

    IF_DECLARATION_NODE,
    ELSE_IF_DECLARATION_NODE,
    ELSE_DECLARATION_NODE,

    SCOPE_NODE,

    VAR_ASSIGN_NODE,
    VAR_UPDATE_NODE,
    VAR_USE_NODE,
    VAR_ARRAY_USE_NODE,
    NULL_USE_NODE,

    VALUE_NODE,
    VALUE_ARRAY_NODE,

    FUNCTION_CALL_NODE,

    COMPARE_NODE,
    INCREASE_NODE,
    MATH_NODE,
    NOT_NODE,
    RETURN_NODE,

    CONTINUE_NODE,
    BREAK_NODE,
    CONVERSION_NODE,
}
