name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Scanner_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Give permissions
        run: chmod +x tests/test_scanner.sh

      - name: Scanner Tests
        run: |
          echo "Compile scanner"
          make
          cd tests
          echo "Run tests"
          ./test_scanner.sh
  
  Parser_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Give permissions
        run: chmod +x tests/test_parser.sh

      - name: Parser Tests
        run: |
          echo "Compile parser"
          make
          cd tests
          echo "Run tests"
          ./test_parser.sh