name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Scanner_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Give permissions
        run: chmod +x tests/test_scanner.sh

      - name: Scanner Tests
        run: make && cd tests && ./test_scanner.sh